install:
  - SET PATH=C:\Ruby%RUBYVER%\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - ridk version
  - gem --version
  - gem install bundler --quiet --no-document
  - bundle install
  # Update to libffi-3.3 since Appveyor version fails on LongDouble specs
  - ridk exec pacman --sync --refresh --needed --noconfirm  mingw-w64-x86_64-libffi mingw-w64-i686-libffi
build: off
build_script:
  - bundle exec rake libffi compile -- %EXTCONFOPTS% || bundle exec rake compile -- %EXTCONFOPTS%
test_script:
  - bundle exec rake test
  - bundle exec rake types_conf && git --no-pager diff
environment:
  matrix:
    - RUBYVER: 25-x64
      EXTCONFOPTS: "--enable-system-libffi"
    - RUBYVER: 26
      EXTCONFOPTS: "--enable-system-libffi"
